name: 'terrajux'

description: 'GitHub Action that runs terrajux'

inputs:
  git_url:
    description: 'The module git URL to pass as the "<giturl>" to terrajux'
    required: true
  v1_ref:
    description: 'The module repository git ref to pass as the "<v1ref>" to terrajux'
    required: true
  v2_ref:
    description: 'The module repository git ref to pass as the "<v2ref>" to terrajux'
    required: true
  subpath:
    description: 'The module repository subpath to pass as the "<subpath>" to terrajux'
    required: true
    default: "."
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.repo }}
    - ${{ inputs.v1ref }}
    - ${{ inputs.v2ref }}
    - ${{ inputs.subpath }}
