name: CI

on: [push]

jobs:
  build:
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: make
  test-main-code:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: make check-tag
    - uses: mdb/terrajux-action@main
      with:
        git_url: "https://github.com/terraform-aws-modules/terraform-aws-iam"
        v1_ref: "v3.15.0"
        v2_ref: "v3.16.0"
        subpath: "."
  publish-prerelease:
    if: github.ref == 'refs/heads/main'
    needs: test-main-code
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - run: make prerelease
      env:
        GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
  publish-container-image:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: test-main-code
    steps:
    - uses: docker/setup-qemu-action@v1
    - uses: docker/setup-buildx-action@v1
    - uses: docker/login-action@v1
      with:
        username: clapclapexcitement
        password: ${{ secrets.DOCKER_HUB_LOGIN }}
    - uses: docker/build-push-action@v2
      id: docker_build
      with:
        push: true
        tags: clapclapexcitement/terrajux-action:latest
    - run: echo ${{ steps.docker_build.outputs.digest }}
  test-container-image:
    if: github.ref == 'refs/heads/main'
    needs: publish-container-image
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@main
    - uses: docker://registry.hub.docker.com/clapclapexcitement/terrajux-action:latest
      with:
        git_url: "https://github.com/terraform-aws-modules/terraform-aws-iam"
        v1_ref: "v3.15.0"
        v2_ref: "v3.16.0"
        subpath: "."
